Fix issue #32 Getting TypeError: 'NoneType' object is not subscriptable
iamkroot/ilc-scraper pull request #33
Opened 2020-09-03 04:54 UTC by krishvk

The error is thrown because of an unexpected line/pattern which is ignored now

2020-09-03 13:10 UTC, iamkroot requested changes
Great work finding a clean and precise solution! 

I recommend improving the commit message a bit. Go through [this](https://www.slideshare.net/mobile/TarinGamberini/commit-messages-goodpractices).

Specifically,
1. The first line should specify the exact change that was made (not the description or number of fixed issue)
2. The message body can elaborate on the reasons and rationale behind the change. 
3. Last line should link to the issue that is closed. (Fixes #32) 

Take a look at the commit history in the master branch to see similar commits which have fixed bugs.

2020-09-04 02:35 UTC, krishvk commented
Will do in sometime @iamkroot

2020-09-05 02:47 UTC, krishvk commented
Can you please check now

2020-09-05 04:55 UTC, iamkroot approved these changes

2020-09-05 05:00 UTC, merged